// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace NoDoxx
{
    internal sealed partial class Vsix
    {
        public const string Id = "NoDoxx.8238cd32-5f52-4ecc-9e2a-026e45f04c3e";
        public const string Name = "NoDoxx";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Eric Johansson";
        public const string Tags = "";
    }
}
